# Generated by Django 3.1.5 on 2021-02-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('proveedor', models.CharField(max_length=200)),
                ('PaisProveedor', models.CharField(choices=[('COL', 'Colombia'), ('VNZ', 'Venezuela'), ('USA', 'Estados Unidos'), ('CHN', 'China'), ('JPN', 'Japon')], max_length=3)),
                ('pais_proveedor', models.CharField(choices=[('COL', 'Colombia'), ('VNZ', 'Venezuela'), ('USA', 'Estados Unidos'), ('CHN', 'China'), ('JPN', 'Japon')], max_length=10)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
